### ISSUE TITLE
Observer crashes

### ISSUE THREAD

**Issue by stphnrdmr** [HWDexperte/ts3observer#52]
https://gist.github.com/stphnrdmr/83e305bc98e1a82e4c24626a3e8aaa7d

**Comment by HWDexperte** [comment]
Will investigate, known bug, should be easy to fix

**Comment by HWDexperte** [comment]
After some investigation and testing, i found out that this will happen under very special circumstances.

If a plugin has moved a client into another channel, it saves the moved client id (clid) ant the channel he comes from (cid). After that the plugin checks every cycle if the condition which triggered the move process is still True.

If true, nothing happens. The client remains into the "to-move" (afk) channel.
Otherwise the action which moved the client expires. If no further condition insists on holding the client in the afk channel, he will be moved back to his original (source) channel.

The problem now is right between this two conditions.

If a client is moved to another channel and leaves the server afterwards (while he is hold in that channel), the action still saves the client_id and tries to move the client back to his original channel.
Since the client is disconnected, this produces the given error message.

This Exception should actually be catched, but this piece of code was missing ... The following fix should prevent the ts3observer from crashing.

**Comment by stphnrdmr** [comment]
Awesome!
